project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nescoba/
      - icon: twitter
        href: https://twitter.com/nicoEscobarV
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

